steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mongodb-loader', './mongodb_loader']
    id: 'Build MongoDB Loader Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mongodb-loader']
    id: 'Push MongoDB Loader Image'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'kubecluster', '--region', 'us-central1', '--project', '$PROJECT_ID']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker', '--quiet']

  - name: 'google/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      kubectl apply -f mongodb-deployment.yaml
    id: 'Deploy to GKE'


  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/mysql-loader', './mysql_loader']
  #   id: 'Build MySQL Loader Image'

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/mysql-loader']
  #   id: 'Push MySQL Loader Image'
  # #  sGKE
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'mongodb-deployment.yaml']
  #   id: 'Deploy MongoDB'
  #   env:
  #   - 'CLOUDSDK_COMPUTE_ZONE=your-zone'
  #   - 'CLOUDSDK_CONTAINER_CLUSTER=your-cluster'

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'mysql-deployment.yaml']
  #   id: 'Deploy MySQL'

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'metabase-deployment.yaml']
  #   id: 'Deploy Metabase'

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'etl-app-deployment.yaml']
  #   id: 'Deploy ETL App'

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'init-mongodb-data-fetcher-deployment.yaml']
  #   id: 'Deploy MongoDB Data Fetcher'

  # # Build the Docker image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY/IMAGE:TAG', '.']

  # # Push the image to Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY/IMAGE:TAG']

