version: '3'
services:
  python-app:
    build: .
    container_name: python-container
    volumes:
      - .:/app
    networks:
      - app-network
  mongodb:
    image: mongo
    container_name: mongodb-container
    volumes:
      - ./datamongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
