version: '3'
services:
   mongodb:
    container_name: mongodb-container
    image: mongo
    volumes:
      - ./datamongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
   init-mongodb-data-fetcher:
    build:
      context: ./mongodb_loader
      dockerfile: dockerfile
    container_name: data-fetcher
    depends_on:
      - mongodb
    volumes:
      - ./mongodb_loader:/app/mongodb_loader 
    networks:
      - app-network
   etl-app:
    container_name: etl-container
    build:
      context: ./mysql_loader
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./mysql_loader:/app/mysql_loader
    command: python /app/mysql_loader/datatransfer_mongodb_mysql.py
    networks:
      - app-network
   mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: hogwarts
    ports:
      - "3306:3306" 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
   metabase:
    image: metabase/metabase
    container_name: metabase-container
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=hogwarts
      - MB_DB_PORT=3306
      - MB_DB_USER=admin
      - MB_DB_PASS=admin
      - MB_DB_HOST=mysql-container
      - MB_DB_USE_SSL=false
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - metabase-data:/metabase-data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  metabase-data: