version: "3"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: hogwarts
    ports:
      - "3306:3306" 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
