apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase
        env:
          - name: MB_DB_TYPE
            value: "mysql"
          - name: MB_DB_DBNAME
            value: "hogwarts"
          - name: MB_DB_PORT
            value: "3306"
          - name: MB_DB_USER
            value: "admin"
          - name: MB_DB_PASS
            value: "admin"
          - name: MB_DB_HOST
            value: "mysql-service"
          - name: MB_DB_USE_SSL
            value: "false"
        ports:
        - containerPort: 3000
